"""Type stub override for AppController.

See ``qt_model.pyi`` for the rationale: PySide6 6.11.0's
``@Property`` + ``@prop.setter`` pattern produces a ``Property``
instance as a class attribute, which the PySide6 stub types as opaque.
This file re-declares every ``@Property`` as a plain instance attribute
so callers can assign to ``controller.skillModel = ...`` and read
``controller.clientFormat`` (a ``str``, not a ``Property``).

This is the root-of-the-cascade fix. It also re-declares the
sub-controller gateways (``config_controller``, ``ui_controller``,
``ops_controller``, etc.) with their concrete types so that chained
access like ``app.ops_controller.foo`` resolves through the
sub-controller's own .pyi (when present) or its runtime type.
"""

from typing import Any, ClassVar

from PySide6.QtCore import QObject, Qt, SignalInstance

from skill_manager.controllers.app_update_controller import AppUpdateController
from skill_manager.controllers.config_controller import ConfigController
from skill_manager.controllers.discovery_controller import DiscoveryController
from skill_manager.controllers.image_inspector_controller import ImageInspectorController
from skill_manager.controllers.ops_controller import OpsController
from skill_manager.controllers.screenshot_controller import ScreenshotController
from skill_manager.controllers.ui_controller import UIController
from skill_manager.controllers.update_controller import UpdateController
from skill_manager.core.file_watch import SkillFolderWatcher
from skill_manager.core.global_hotkey import GlobalHotkeyManager
from skill_manager.core.image_provider import ScreenshotImageProvider
from skill_manager.core.models import SkillModel

class AppController(QObject):
    # Core State Signals
    skillModelChanged: ClassVar[SignalInstance]
    selectedSkillChanged: ClassVar[SignalInstance]
    isLoadingChanged: ClassVar[SignalInstance]
    statusMessageChanged: ClassVar[SignalInstance]
    sourcesChanged: ClassVar[SignalInstance]
    projectsChanged: ClassVar[SignalInstance]
    discoveredProjectsChanged: ClassVar[SignalInstance]
    currentProjectChanged: ClassVar[SignalInstance]
    clientFormatChanged: ClassVar[SignalInstance]
    categoriesChanged: ClassVar[SignalInstance]
    clientFormatsChanged: ClassVar[SignalInstance]
    defaultClientChanged: ClassVar[SignalInstance]
    customCollectionsChanged: ClassVar[SignalInstance]
    updateResultsChanged: ClassVar[SignalInstance]
    updatePackagesChanged: ClassVar[SignalInstance]
    isPackageOnlyChanged: ClassVar[SignalInstance]
    currentViewChanged: ClassVar[SignalInstance]
    windowWidthChanged: ClassVar[SignalInstance]
    windowHeightChanged: ClassVar[SignalInstance]
    windowXChanged: ClassVar[SignalInstance]
    windowYChanged: ClassVar[SignalInstance]
    darkModeChanged: ClassVar[SignalInstance]
    startupViewChanged: ClassVar[SignalInstance]
    rememberFiltersChanged: ClassVar[SignalInstance]
    reducedMotionChanged: ClassVar[SignalInstance]
    compactListRowsChanged: ClassVar[SignalInstance]
    skillPackageAutoUpdateChanged: ClassVar[SignalInstance]
    skillPackageAutoUpdateModeChanged: ClassVar[SignalInstance]
    statsChanged: ClassVar[SignalInstance]
    shortcutsChanged: ClassVar[SignalInstance]
    isRecordingShortcutChanged: ClassVar[SignalInstance]
    commandUpdateConflict: ClassVar[SignalInstance]
    commandUpdateCompleted: ClassVar[SignalInstance]

    # --- Gateway Properties (sub-controllers, exposed via @Property(QObject)) ---
    ui_controller: UIController
    config_controller: ConfigController
    ops_controller: OpsController
    update_controller: UpdateController
    discovery_controller: DiscoveryController
    app_update_controller: AppUpdateController
    screenshot_controller: ScreenshotController
    image_inspector_controller: ImageInspectorController

    # --- Core Properties ---
    skillModel: SkillModel
    libraryModel: SkillModel
    quickCopyModel: SkillModel
    selectedSkill: dict
    isLoading: bool
    isTesting: bool
    statusMessage: str
    sources: list[str]
    projects: list[str]
    syncingProjects: list[str]
    clientFormat: str
    defaultClient: str
    categories: list[str]
    discoveredProjects: list[str]
    updatePackages: list[dict]
    projectAliases: dict
    updateResults: list[dict]
    statsUpToDate: int
    statsOutdated: int
    statsMissing: int

    # --- Proxy Properties (QML compat) ---
    currentProject: str
    currentView: str
    windowWidth: int
    windowHeight: int
    windowX: int
    windowY: int
    darkMode: bool
    startupView: str
    rememberFilters: bool
    reducedMotion: bool
    compactListRows: bool
    shortcutSearch: str
    shortcutSelectAll: str
    shortcutClearSelection: str
    shortcutCopy: str
    shortcutRefresh: str
    shortcutArchive: str
    shortcutDelete: str
    shortcutExpandAll: str
    shortcutCollapseAll: str
    shortcutTopOfList: str
    shortcutQuickCopyView: str
    shortcutLibraryView: str
    shortcutUpdatesView: str
    shortcutSettingsView: str
    shortcutThemeToggle: str
    shortcutScreenshot: str
    isRecordingShortcut: bool
    logoSource: str
    updateProjects: list[dict]
    clientFormats: list[str]
    customCollections: dict
    projectLabels: list[str]
    isPackageOnly: Qt.CheckState

    # --- Internal state (set in __init__) ---
    ui: UIController
    config_mgr: ConfigController
    ops: OpsController
    screenshot_provider: ScreenshotImageProvider
    screenshot: ScreenshotController
    image_inspector: ImageInspectorController
    updates: UpdateController
    discovery: DiscoveryController
    app_updater: AppUpdateController
    global_hotkey: GlobalHotkeyManager
    task_runner: Any
    _config: Any
    _library_model: SkillModel
    _quick_copy_model: SkillModel
    _selected_skill: dict
    _is_loading: bool
    _status_message: str
    _discovered_projects: list[str]
    _categories: list[str]
    _clipboard: Any
    _is_recording_shortcut: bool
    _client_format: str
    _sources: list[str]
    _projects: list[str]
    _project_aliases: dict
    _update_packages: list[dict]
    _custom_collections: dict
    _current_project_label: str
    _archive_paths: list[str]
    _starred_paths: list[str]
    _syncing_projects: list[str]
    _update_results: list[dict]
    _stats_up_to_date: int
    _stats_outdated: int
    _stats_missing: int
    _watcher: SkillFolderWatcher | None
    _scheduler: Any
    _hotkey_id_screenshot: int

    def __init__(self, skip_initial_load: bool = ..., config: Any = ...) -> None: ...
    def setCurrentProject(self, label: str) -> None: ...
    def setDefaultClient(self, f: str) -> None: ...
    def load_initial_data(self) -> None: ...
    def getLogoSource(self, f: str) -> str: ...
    def getAssetUri(self, p: str) -> str: ...
    def setViewFilter(self, k: str, v: str) -> None: ...
    def setViewFilterForView(self, view: str, k: str, v: str) -> None: ...
    def clearViewFilters(self) -> None: ...
    def selectSkill(self, i: int) -> None: ...
    def clearVisibleSelection(self) -> None: ...
    def selectAllVisibleSkills(self) -> None: ...
    def toggleAllVisibleCategories(self) -> None: ...
    def launchSkill(self, p: str) -> None: ...
    def openPath(self, p: str) -> None: ...
    def resetUiState(self) -> None: ...
    def setClientFormat(self, f: str) -> None: ...
    def setStartupView(self, v: str) -> None: ...
    def setRememberFilters(self, b: bool) -> None: ...
    def setReducedMotion(self, b: bool) -> None: ...
    def setCompactListRows(self, b: bool) -> None: ...
    def addSource(self, u: str) -> None: ...
    def removeSource(self, p: str) -> None: ...
    def removeSourceByIndex(self, i: int) -> None: ...
    def addProject(self, u: str) -> None: ...
    def removeProject(self, p: str) -> None: ...
    def reorderProjects(self, from_index: int, to_index: int) -> None: ...
    def removeUpdateProject(self, i: int) -> None: ...
    def setProjectAlias(self, p: str, a: str) -> None: ...
    def verifyGitPackage(self, u: str, t: str | None = ...) -> str: ...
    def setShortcut(self, a: str, s: str) -> None: ...
    def resetShortcuts(self) -> None: ...
    def saveCustomCollection(self, n: str, p: list, proj: list) -> None: ...
    def deleteCustomCollection(self, n: str) -> None: ...
    def applyCollectionSelection(self, n: str) -> None: ...
    def getCollectionPaths(self, n: str) -> list: ...
    def getCollectionProjects(self, n: str) -> list: ...
    def checkMissingSkills(self, n: str) -> str: ...
    def copyMissingSkills(self, n: str, projects: list) -> None: ...
    def toggleCurrentSkillArchive(self) -> None: ...
    def toggleCurrentSkillStarred(self) -> None: ...
    def copySkillToClipboard(self, p: str) -> None: ...
    def copyCurrentSelectionOrFocusedSkill(self) -> None: ...
    def copySelectedSkillsToClipboard(self) -> None: ...
    def copyTextToClipboard(self, c: str) -> None: ...
    def copySkillReference(self, s: dict, a: str = ...) -> None: ...
    def deleteSkill(self, p: str) -> None: ...
    def deleteSelectedSkills(self) -> None: ...
    def archiveSelectedSkills(self) -> None: ...
    def copySelectedSkillsToProject(self, p: str) -> None: ...
    def copySelectedSkillsToProjectTemporarily(self, p: str) -> None: ...
    def updateCustomCommandFull(self, lp: str, n: str, b: str, cat: str, proj: str, on_conflict: str = ...) -> None: ...
    def notify_command_updated(self, old_path: str, new_path: str) -> None: ...
    def createCustomCommand(self, n: str, b: str, pl: str, cat: str) -> None: ...
    def addToArchive(self, p: str) -> None: ...
    def updateNow(self) -> None: ...
    def scanForUpdates(self) -> None: ...
    def updateAllOutdated(self) -> None: ...
    def updateSkillInProject(self, s: str, p: str) -> None: ...
    def runPackageUpdate(self, i: int) -> None: ...
    def syncProject(self, p: str) -> None: ...
    def addUpdatePackage(self, n: str) -> None: ...
    def addSkillPackage(self, d: dict) -> None: ...
    def updateUpdatePackage(self, i: int, d: dict) -> None: ...
    def removeUpdatePackage(self, i: int) -> None: ...
    def clearPackageJustFinished(self, i: int) -> None: ...
    def loadInitialData(self) -> None: ...
    def logDiagnostic(self, level: str, category: str, msg: str) -> None: ...
    def logDiagnosticEvent(self, level: str, category: str, msg: str) -> None: ...
    def getCategoryEmoji(self, category_name: str) -> str: ...
    def refreshSkills(self) -> None: ...
    def getProjectLabel(self, path: str) -> str: ...
    def on_quit(self) -> None: ...
    def _run_startup_package_scan(self) -> None: ...
    def _update_package_scheduler(self) -> None: ...
    def _on_client_format_changed(self) -> None: ...
    def _on_projects_changed(self) -> None: ...
    def _set_status(self, msg: str) -> None: ...
    def _setup_global_hotkeys(self) -> None: ...
    def _on_global_hotkey(self, hotkey_id: int) -> None: ...
    def _on_shortcuts_changed(self) -> None: ...

# Module-level constants and entry point
_app_mutex: Any
HAS_PYWINSTYLES: bool
logger: Any

def main() -> None: ...

# Re-exports used by tests/main
def __getattr__(name: str) -> Any: ...
