"""Type stub override for ConfigController.

See ``qt_model.pyi`` and ``app.pyi`` for the rationale: PySide6 6.11.0's
``@Property`` + ``@prop.setter`` pattern produces a ``Property`` instance
as a class attribute, which the PySide6 stub types as opaque (no
settable surface). This file re-declares the writable properties as
plain instance attributes so callers can assign to them
(``controller.scrollSpeedMultiplier = 2.0``) without triggering
false-positive ``reportAttributeAccessIssue`` errors.

The ``_set_config_value`` helper signature is re-declared with
``SignalInstance | None`` instead of the (incorrect) ``Signal`` class —
the runtime argument is always a ``SignalInstance`` (from the
``*Changed`` class attribute), not the ``Signal`` factory class.
"""

from typing import Any, ClassVar

from PySide6.QtCore import QObject, SignalInstance

from skill_manager.app import AppController

class ConfigController(QObject):
    # Signals
    shortcutsChanged: ClassVar[SignalInstance]
    isRecordingShortcutChanged: ClassVar[SignalInstance]
    updateProjectsChanged: ClassVar[SignalInstance]
    clientFormatsChanged: ClassVar[SignalInstance]
    customCollectionsChanged: ClassVar[SignalInstance]
    scrollSpeedMultiplierChanged: ClassVar[SignalInstance]
    skillPackageAutoUpdateModeChanged: ClassVar[SignalInstance]
    autoMinimizeOnScreenshotChanged: ClassVar[SignalInstance]
    autoMinimizeOnQuickCopyChanged: ClassVar[SignalInstance]
    temporaryScreenshotsChanged: ClassVar[SignalInstance]
    diagnosticLoggingChanged: ClassVar[SignalInstance]

    # Writable properties (have @propname.setter in config_controller.py)
    scrollSpeedMultiplier: float
    skillPackageAutoUpdateMode: str
    autoMinimizeOnScreenshot: bool
    autoMinimizeOnQuickCopy: bool
    temporaryScreenshots: bool
    diagnosticLogging: bool
    isRecordingShortcut: bool
    topBarClients: list[str]

    # Read-only properties
    project_aliases: dict
    shortcutSearch: str
    shortcutSelectAll: str
    shortcutClearSelection: str
    shortcutCopy: str
    shortcutRefresh: str
    shortcutArchive: str
    shortcutDelete: str
    shortcutExpandAll: str
    shortcutCollapseAll: str
    shortcutTopOfList: str
    shortcutQuickCopyView: str
    shortcutLibraryView: str
    shortcutUpdatesView: str
    shortcutSettingsView: str
    shortcutThemeToggle: str
    shortcutScreenshot: str
    availableClientFormats: list[str]
    clientFormats: list[str]
    customCollections: list[str]
    updateProjects: list[dict]
    projectLabels: list[str]

    # State
    app: AppController
    config: Any
    _cached_update_projects: list[dict] | None
    _cached_project_labels: list[str] | None

    def __init__(self, app: AppController) -> None: ...
    def _set_config_value(
        self, key: str, value: Any, signal: SignalInstance | None = ...
    ) -> bool: ...
    def _normalize_path(self, raw_url: str) -> str: ...
    def _invalidate_project_cache(self) -> None: ...
    def _emit_projects_changed(self) -> None: ...
    def _emit_collections_changed(self) -> None: ...
    def addSource(self, url: str) -> None: ...
    def removeSource(self, path: str) -> None: ...
    def removeSourceByIndex(self, index: int) -> None: ...
    def addProject(self, url: str) -> None: ...
    def removeProject(self, path: str) -> None: ...
    def reorderProjects(self, from_index: int, to_index: int) -> None: ...
    def removeUpdateProject(self, index: int) -> None: ...
    def setProjectAlias(self, path: str, alias: str) -> None: ...
    def verifyGitPackage(self, url: str, token: str | None = ...) -> str: ...
    def get_shortcut(self, key: str) -> str: ...
    def setShortcut(self, action: str, sequence: str) -> None: ...
    def resetShortcuts(self) -> None: ...
    def isShortcutEnabled(self, action: str) -> bool: ...
    def setShortcutEnabled(self, action: str, enabled: bool) -> None: ...
    def setStatus(self, msg: str) -> None: ...
    def saveCustomCollection(self, name: str, paths: list, projects: list) -> None: ...
    def deleteCustomCollection(self, name: str) -> None: ...
    def applyCollectionSelection(self, name: str) -> None: ...
    def getCollectionPaths(self, name: str) -> list: ...
    def getCollectionProjects(self, name: str) -> list: ...
    def checkMissingSkills(self, name: str) -> str: ...
    def copyMissingSkills(self, name: str, project_labels: list) -> None: ...
    def getCollectionsDiagnostic(self) -> str: ...
    def getProjectResolutionTable(self) -> str: ...
    def getProjectPath(self, label: str) -> str: ...
    def getProjectLabel(self, path: str) -> str: ...
    def save_cache(self, data: dict) -> None: ...
    def load_cache(self) -> dict: ...
    def getDiagnosticLogPath(self) -> str: ...
    def getRecentDiagnosticEvents(self, count: int = ...) -> str: ...
    def exportDiagnosticBundle(self, output_dir: str = ...) -> str: ...
    def clearDiagnosticLogs(self) -> None: ...
    def getDiagnosticCounts(self) -> str: ...
    def getDiagnosticHealthStatus(self) -> str: ...
    def getRecentEventsHuman(self, count: int = ...) -> str: ...
