"""Type stub override for OpsController.

This controller has no ``@Property`` declarations of its own — its
behaviour is methods-only. The stub is intentionally minimal; it
exists to ensure that callers see the concrete ``AppController``
type on ``self.app`` and to give pyright a complete class surface
when ``app.pyi`` is present (which would otherwise hide members
declared only in the ``.py``).
"""

from typing import Any, ClassVar

from PySide6.QtCore import QObject, SignalInstance

from skill_manager.app import AppController

class OpsController(QObject):
    # Signals
    minimizeAppRequested: ClassVar[SignalInstance]

    # State
    app: AppController

    def __init__(self, app: AppController) -> None: ...
    def _maybeMinimizeOnCopy(self) -> None: ...
    def _updateModelsProperty(self, path: str, key: str, value: Any) -> None: ...
    def _toggle_skill_boolean(
        self,
        attr_name: str,
        path_list: list[str],
        persist_fn: Any,
        event_name: str,
    ) -> None: ...
    def _saveArchive(self) -> None: ...
    def _saveStarred(self) -> None: ...
    def _merge_discovered_skills(self, discovered: list) -> None: ...
    def _refresh_selected_skill(self, local_path: str, rename_path: str | None = None) -> None: ...
    def toggleArchive(self) -> None: ...
    def toggleCurrentSkillArchive(self) -> None: ...
    def toggleStarred(self) -> None: ...
    def toggleCurrentSkillStarred(self) -> None: ...
    def deleteSkills(self, items: list) -> None: ...
    def deleteSkill(self, path: str) -> None: ...
    def deleteSelectedSkills(self) -> None: ...
    def archiveSelectedSkills(self) -> None: ...
    def addToArchive(self, skill_local_path: str) -> None: ...
    def cleanup_temp_copies(self) -> None: ...
    def cleanup_temp_screenshots(self) -> None: ...
    def copySelectedSkillsToProject(self, project_path: str, is_temporary: bool = ...) -> None: ...
    def copySelectedSkillsToProjectTemporarily(self, project_path: str) -> None: ...
    def copySkillToClipboard(self, path: str) -> None: ...
    def copyCurrentSelectionOrFocusedSkill(self) -> None: ...
    def copySelectedSkillsToClipboard(self) -> None: ...
    def copyTextToClipboard(self, content: str) -> None: ...
    def copySkillReference(self, skill: Any, arg: str = ...) -> None: ...
    def copyCollectionToClipboard(self, name: str) -> None: ...
    def createCustomCommand(
        self, name: str, body: str, project_label: str, category: str
    ) -> None: ...
    def updateCustomCommandFull(self, lp: str, n: str, b: str) -> None: ...
