"""Type stub override for OpsController.

This controller has no ``@Property`` declarations of its own — its
behaviour is methods-only. The stub exists to ensure that callers see
the concrete ``AppController`` type on ``self.app`` and to give pyright
a complete class surface when ``app.pyi`` is present (which would
otherwise hide members declared only in the ``.py``).
"""

from pathlib import Path
from typing import Any, ClassVar

from PySide6.QtCore import QObject, SignalInstance

from skill_manager.app import AppController

class OpsController(QObject):
    # Signals
    minimizeAppRequested: ClassVar[SignalInstance]
    commandPendingRemovals: ClassVar[SignalInstance]  # str, list
    commandSkillsCarryPrompt: ClassVar[SignalInstance]  # str, str, str

    # State
    app: AppController
    _is_deleting: bool
    _pending_command_update: dict | None

    def __init__(self, app: AppController) -> None: ...

    # ── Toggles ────────────────────────────────────────────────────────
    def _toggle_skill_boolean(
        self,
        attr_name: str,
        path_list: list[str],
        persist_fn: Any,
        event_name: str,
    ) -> None: ...
    def toggleArchive(self) -> None: ...
    def toggleCurrentSkillArchive(self) -> None: ...
    def toggleStarred(self) -> None: ...
    def toggleCurrentSkillStarred(self) -> None: ...
    def archiveSelectedSkills(self) -> None: ...
    def addToArchive(self, skill_local_path: str) -> None: ...
    def _saveArchive(self) -> None: ...
    def _saveStarred(self) -> None: ...
    def _updateModelsProperty(self, path: str, key: str, value: Any) -> None: ...

    # ── Delete ─────────────────────────────────────────────────────────
    def deleteSkills(self, items: list) -> None: ...
    def deleteSkill(self, path: str) -> None: ...
    def deleteSkillsByPaths(self, paths: list[str]) -> None: ...
    def deleteSelectedSkills(self) -> None: ...
    def deleteSkillFromProjects(self, path: str, project_labels: list[str]) -> None: ...
    def deleteCustomCommand(self, command_name: str, project_labels: list[str]) -> None: ...
    def cleanup_temp_copies(self) -> None: ...
    def cleanup_temp_screenshots(self) -> None: ...

    # ── Copy ───────────────────────────────────────────────────────────
    def copySelectedSkillsToProject(self, project_path: str, is_temporary: bool = ...) -> None: ...
    def copySelectedSkillsToProjectTemporarily(self, project_path: str) -> None: ...
    def copyCommandsToProjectWithCarry(
        self, project_path: str, command_paths_json: str
    ) -> None: ...
    def confirmCommandSkillsCarry(
        self, project_path: str, command_paths_json: str, confirmed_skills_json: str
    ) -> None: ...

    # ── Clipboard ──────────────────────────────────────────────────────
    def copySkillToClipboard(self, path: str) -> None: ...
    def copyCurrentSelectionOrFocusedSkill(self) -> None: ...
    def copySelectedSkillsToClipboard(self) -> None: ...
    def copyTextToClipboard(self, content: str) -> None: ...
    def copySkillReference(self, skill: dict, arg: str = ...) -> None: ...
    def copyCollectionToClipboard(self, name: str) -> None: ...
    def _maybeMinimizeOnCopy(self) -> None: ...
    def _send_paste_to_focused_window(self) -> None: ...

    # ── Commands ───────────────────────────────────────────────────────
    def createCustomCommand(
        self, name: str, body: str, project_labels: list[str], category: str
    ) -> str: ...
    def updateCustomCommandFull(
        self,
        local_path: str,
        name: str,
        body: str,
        category: str,
        project_labels: list[str],
        on_conflict: str = ...,
        confirmed_removals: list[str] | None = ...,
    ) -> None: ...
    def confirmCommandRemovals(self, local_path: str, confirmed_labels: list[str]) -> None: ...
    def commandProjectsForPath(self, local_path: str) -> list[str]: ...
    def _get_all_known_skills(self) -> list: ...
    def _snapshot_affected_paths(self, affected_project_paths: set[Path]) -> set[str]: ...
    def _emit_missing_skills_prompt(
        self, proj_root: Path, command_path: Path, body: str, tag: str
    ) -> None: ...

    # ── Inspector ──────────────────────────────────────────────────────
    def getReferencedSkillsForCommand(self, command_path: str) -> list: ...
    def getSkillReferenceRanges(self, command_path: str) -> list: ...
    def applySkillHighlights(
        self, target: QObject | str, ranges_json: str, focused_index: int = ...
    ) -> None: ...
    def clearSkillHighlights(self, target: QObject | str) -> None: ...
    def _find_qml_text_edit(self, object_name: str) -> Any: ...

    # ── Sync ───────────────────────────────────────────────────────────
    def _merge_discovered_skills(self, discovered: list) -> None: ...
    def _refresh_selected_skill(self, local_path: str, rename_path: str | None = None) -> None: ...
    def _apply_targeted_refresh(
        self, affected_project_paths: set[Path], all_discovered: list
    ) -> set[str]: ...
    def skillProjectsForPath(self, local_path: str) -> list[str]: ...
