"""Type stub override for UIController.

See ``qt_model.pyi`` and ``app.pyi`` for the rationale: PySide6 6.11.0's
``@Property`` + ``@prop.setter`` pattern produces a ``Property`` instance
as a class attribute, which the PySide6 stub types as opaque (no
settable surface). This file re-declares the writable properties as
plain instance attributes so callers can assign to them
(``controller.windowWidth = 800``) without triggering false-positive
``reportAttributeAccessIssue`` errors.
"""

from typing import Any, ClassVar

from PySide6.QtCore import QObject, QTimer, SignalInstance

from skill_manager.app import AppController
from skill_manager.core.schemas import UIStateRecord

class UIController(QObject):
    # Signals
    currentViewChanged: ClassVar[SignalInstance]
    windowWidthChanged: ClassVar[SignalInstance]
    windowHeightChanged: ClassVar[SignalInstance]
    windowXChanged: ClassVar[SignalInstance]
    windowYChanged: ClassVar[SignalInstance]
    darkModeChanged: ClassVar[SignalInstance]
    startupViewChanged: ClassVar[SignalInstance]
    rememberFiltersChanged: ClassVar[SignalInstance]
    reducedMotionChanged: ClassVar[SignalInstance]
    compactListRowsChanged: ClassVar[SignalInstance]
    inspectorWidthChanged: ClassVar[SignalInstance]

    # Writable properties (have @propname.setter in ui_controller.py)
    currentView: str
    windowWidth: int
    windowHeight: int
    windowX: int
    windowY: int
    darkMode: bool
    startupView: str
    rememberFilters: bool
    reducedMotion: bool
    compactListRows: bool
    inspectorWidth: int

    # Read-only properties
    logoSource: str

    # State
    app: AppController
    config: Any
    _state: UIStateRecord
    _save_timer: QTimer

    def __init__(self, app: AppController) -> None: ...
    def setInspectorWidth(self, value: int) -> None: ...
    def getLogoSource(self, fmt: str) -> str: ...
    def setClientFormat(self, f: str) -> None: ...
    def setStartupView(self, v: str) -> None: ...
    def setRememberFilters(self, b: bool) -> None: ...
    def setReducedMotion(self, b: bool) -> None: ...
    def setCompactListRows(self, b: bool) -> None: ...
    def triggerSave(self) -> None: ...
    def saveUiState(self) -> None: ...
    def resetUiState(self) -> None: ...
    @staticmethod
    def _normalizeViewName(value: str) -> str: ...
    def getAssetUri(self, path: str) -> str: ...
    def openPath(self, path: str) -> None: ...
    def launchSkill(self, path: str) -> None: ...
    def selectSkill(self, index: int) -> None: ...
    def selectAllVisibleSkills(self) -> None: ...
    def clearVisibleSelection(self) -> None: ...
    def toggleAllVisibleCategories(self) -> None: ...
    def setViewFilter(self, filter_type: str, value: str) -> None: ...
    def setViewFilterForView(self, view: str, filter_type: str, value: str) -> None: ...
    def clearViewFilters(self) -> None: ...
    def _modelForView(self, view: str) -> Any: ...
    def _setViewFilterForModel(self, model: Any, filter_type: str, value: str) -> None: ...
    def _clearAllViewFilters(self) -> None: ...
