CATEGORIES = {
    "Core Workflow": [
        "plan",
        "planning",
        "brainstorm",
        "brainstorming",
        "constructive work",
        "kaizen",
        "starred",
        "questions",
        "underspecified",
        "verification",
        "completion",
        "task",
        "workflow",
        "conductor",
        "build",
        "project guidelines",
        "sharp edges",
        "speckit",
        "updater",
    ],
    "Developer Tools": [
        "git",
        "github",
        "pr",
        "pull request",
        "commit",
        "issue",
        "dx",
        "developer experience",
        "file organizer",
        "vexor",
        "semantic file discovery",
        "cli",
        "tool",
        "tools",
        "comprehensive review",
        "environment setup",
        "app-builder",
        "orchestrator",
        "vscode",
        "extension",
        "reverse engineer",
        "code review",
        "oss",
        "open source",
        "skill smith",
    ],
    "Debugging": [
        "debug",
        "debugging",
        "error",
        "stack traces",
        "bug",
        "error detective",
        "logs",
        "root cause",
    ],
    "Architecture": [
        "architect",
        "senior architect",
        "project architect",
        "architecture",
        "architecture diagram",
        "architecture patterns",
        "system design",
        "c4",
        "adr",
        "decision record",
        "domain-driven",
        "ddd",
        "cqrs",
        "event sourcing",
        "bounded context",
        "monorepo",
        "patterns",
        "composition",
    ],
    "Code Quality": [
        "technical debt",
        "legacy",
        "modernizer",
        "refactor",
        "clean code",
        "code quality",
        "simplify",
        "simplifier",
    ],
    "Security": [
        "security",
        "hack",
        "vulnerability",
        "pentest",
        "penetration",
        "auth",
        "xss",
        "threat",
        "risk",
        "attack",
        "red team",
        "active directory",
        "kerberos",
        "forensics",
        "incident response",
        "privilege escalation",
        "secrets",
        "credentials",
        "mtls",
        "zero-trust",
        "shodan",
        "semgrep",
        "permission",
        "ciso",
        "file path traversal",
        "directory traversal",
        "sentinel",
        "auditoria",
    ],
    "Compliance": ["compliance", "audit", "access review", "pci", "policy"],
    "Web Development": [
        "web",
        "frontend",
        "react",
        "next.js",
        "tailwind",
        "css",
        "ui",
        "ux",
        "fullstack",
        "angular",
        "vue",
        "html",
        "website",
        "portfolio",
        "wordpress",
        "three.js",
        "threejs",
        "webgl",
        "laravel",
        "bullmq",
        "node.js",
        "nodejs",
        "redis",
        "popup",
        "signup",
        "full stack",
    ],
    "Mobile Development": [
        "mobile",
        "ios",
        "android",
        "flutter",
        "expo",
        "react native",
        "swift",
        "swiftui",
        "swiftpm",
        "app store",
        "aso",
        "kotlin",
    ],
    "Desktop Development": ["macos", "desktop", "electron", "avalonia", "makepad", "robius"],
    "AI": [
        "ai",
        "ia",
        "llm",
        "rag",
        "prompt",
        "model",
        "claude",
        "openai",
        "gemini",
        "anthropic",
        "hugging face",
        "vision model",
        "computer vision",
        "yolo",
        "sam",
        "notebooklm",
        "deep learning",
        "doc2math",
        "cirq",
        "quantum",
        "jeppa",
        "cnn",
        "research",
    ],
    "Agents": [
        "agent",
        "agents",
        "subagent",
        "subagents",
        "mcp",
        "crewai",
        "langchain",
        "context window",
        "agentes",
    ],
    "Game Development": [
        "game",
        "unity",
        "godot",
        "unreal",
        "bevy",
        "ecs",
        "entity component system",
    ],
    "Backend Development": ["backend", "rails", "node", "api", "fastapi", "full-stack"],
    "Programming Languages": [
        "python",
        "typescript",
        "javascript",
        "rust",
        "go",
        "golang",
        "c-pro",
        " c code",
        "c++",
        "c#",
        "java",
        "ruby",
        "php",
        "elixir",
        "haskell",
        "julia",
        "memory safety",
        "memory-safe",
        "functional programming",
        "fp",
        "fp-ts",
        "either",
        "taskeither",
    ],
    "Shell Scripting": ["posix", "bash", "powershell", "busybox", "windows", "shell", "jq"],
    "Embedded Systems": ["embedded", "firmware", "arm cortex", "microcontroller"],
    "Localization": ["i18n", "localization", "translation", "locale", "rtl"],
    "Migration": ["migration", "code migration", "framework migration"],
    "Product Management": [
        "product",
        "startup",
        "saas",
        "micro-saas",
        "jtbd",
        "jobs-to-be-done",
        "jobs to be done",
        "customer",
        "market",
        "competitive",
        "brand",
        "persona",
        "idea",
        "darwin",
        "personal tool",
        "sred",
    ],
    "Business Strategy": [
        "business",
        "sales",
        "cro",
        "monetization",
        "pricing",
        "price",
        "churn",
        "retention",
        "growth",
    ],
    "Psychology": [
        "psychology",
        "psychologist",
        "identity",
        "trust",
        "calibrator",
        "assumption",
        "auditor",
        "first-principles",
        "emotional arc",
        "loss aversion",
        "objection",
        "pitch",
        "scarcity",
        "urgency",
        "sequence",
    ],
    "Careers": ["interview", "job search", "resume", "career"],
    "Marketing": [
        "marketing",
        "seo",
        "ads",
        "ad creative",
        "paid ads",
        "google ads",
        "meta",
        "linkedin",
        "tiktok",
        "influencer",
        "lead generation",
        "leads",
        "cold email",
        "copywriting",
        "headline",
        "subject line",
        "campaign",
        "audience",
        "brand reputation",
        "aso",
        "awareness",
    ],
    "Social Media": [
        "social",
        "twitter",
        "youtube",
        "publisher",
        "x/twitter",
        "instagram",
        "telegram",
        "botfather",
    ],
    "DevOps": [
        "devops",
        "ci/cd",
        "ci",
        "cd",
        "deploy",
        "deployment",
        "on-call",
        "runbook",
        "incident",
        "slack",
        "tmux",
    ],
    "Cloud Infrastructure": [
        "docker",
        "kubernetes",
        "k8s",
        "aws",
        "azure",
        "gcp",
        "cloud",
        "cloudflare",
        "terraform",
        "linux",
        "server",
        "istio",
        "service mesh",
    ],
    "Observability": [
        "observability",
        "monitor",
        "monitoring",
        "prometheus",
        "slo",
        "tracing",
        "jaeger",
        "tempo",
        "grafana",
        "dashboard",
    ],
    "Build Systems": ["bazel", "nx", "turborepo"],
    "Background Jobs": ["inngest", "background jobs", "queues", "durable execution"],
    "Performance": ["performance", "performance bottlenecks", "performance optimizer", "profiling"],
    "Data": [
        "data",
        "vector",
        "warehouse",
        "forecast",
        "analysis",
        "analyze",
        "matplotlib",
        "visualization",
        "math",
        "matematico",
    ],
    "Databases": ["sql", "postgres", "mysql", "database", "dbt"],
    "Analytics": ["analytics", "backtesting", "spreadsheet", "xlsx"],
    "Design": [
        "design",
        "canvas",
        "canva",
        "art",
        "figma",
        "theme",
        "visual",
        "hig",
        "human interface guidelines",
        "viboscope",
    ],
    "Content": [
        "content",
        "writing",
        "blog",
        "article",
        "video",
        "audio",
        "gif",
        "favicon",
        "unsplash",
        "remotion",
        "portfolio",
        "rsvp",
        "speed reader",
    ],
    "Diagrams": ["mermaid", "diagram"],
    "Documentation": [
        "documentation",
        "docs",
        "readme",
        "wiki",
        "onboarding",
        "obsidian",
        "markdown",
        "latex",
        "paper",
        "docx",
        "pptx",
        "office",
        "document",
    ],
    "Knowledge Management": [
        "summarizer",
        "explain",
        "socratic",
        "bullet",
        "knowledge",
        "context",
        "context save",
        "context restore",
        "diary",
        "logger",
        "thoughts",
    ],
    "Communications": [
        "communication",
        "communication mode",
        "internal comms",
        "communications",
        "brief",
        "terse",
        "caveman",
        "status reports",
    ],
    "Logistics": ["logistics", "freight", "carrier", "returns", "reverse logistics"],
    "Inventory": ["inventory", "demand planning", "warehouse"],
    "Procurement": ["procurement", "purchase", "energy procurement"],
    "Manufacturing": ["production scheduling", "manufacturing"],
    "ERP": ["odoo", "erp", "timesheet"],
    "Quality Control": ["quality control", "non-conformance"],
    "Billing": ["billing", "invoice"],
    "Payments": ["payment", "paypal", "stripe", "tax"],
    "Finance": ["finance", "financial", "trading", "investment", "buffett"],
    "Web3": [
        "blockchain",
        "web3",
        "defi",
        "nft",
        "smart contract",
        "bitcoin",
        "lightning",
        "wallet",
    ],
    "Legal": [
        "legal",
        "law",
        "contract",
        "compliant",
        "jurid",
        "direito",
        "advogado",
        "criminal",
        "trabalhista",
        "tributario",
        "consumidor",
        "imobiliario",
        "civil",
        "leilao",
        "leilões",
        "edital",
        "nulidades",
        "cpc",
        "lei",
        "leiloeiro",
        "avaliacao",
    ],
    "Human Resources": ["employment", "hr", "payroll"],
    "Health": [
        "health",
        "medical",
        "clinical",
        "hospital",
        "emergency",
        "medical card",
        "goal analyzer",
        "健康",
        "医疗",
        "急救",
    ],
    "Fitness": ["fitness", "nutrition", "weightloss", "营养"],
    "Sleep": ["sleep", "睡眠"],
    "Mental Health": ["mental health", "心理"],
    "Sexual Health": ["sexual health"],
    "Oral Health": ["oral health", "口腔"],
    "Occupational Health": ["occupational health"],
    "Rehabilitation": ["rehabilitation", "康复"],
    "Travel Health": ["travel health"],
    "Traditional Medicine": ["tcm", "体质"],
    "Testing": [
        "test",
        "testing",
        "automation",
        "qa",
        "e2e",
        "playwright",
        "cypress",
        "jest",
        "tdd",
        "validation",
        "acceptance",
        "verify",
    ],
    "Linting": ["shellcheck", "linting", "lint"],
    "Personas": [
        "persona",
        "steve jobs",
        "elon musk",
        "bill gates",
        "geoffrey hinton",
        "yann lecun",
        "ilya sutskever",
        "simula",
        "simulate",
    ],
    "Uncategorized": [],
}

MAIN_CATEGORIES_MAPPING = {
    "🛠️ Core Engineering & Technology": [
        "AI",
        "Agents",
        "Architecture",
        "Backend Development",
        "Cloud Infrastructure",
        "DevOps",
        "Developer Tools",
        "Programming Languages",
        "Web Development",
        "Mobile Development",
        "Desktop Development",
        "Embedded Systems",
        "Web3",
        "Game Development",
        "Shell Scripting",
        "Build Systems",
        "Background Jobs",
    ],
    "📈 Business & Operations": [
        "Business Strategy",
        "Marketing",
        "Product Management",
        "Finance",
        "Legal",
        "Compliance",
        "Logistics",
        "Procurement",
        "Billing",
        "Payments",
        "ERP",
        "Human Resources",
        "Inventory",
        "Manufacturing",
        "Careers",
    ],
    "🛡️ Quality & Data": [
        "Security",
        "Testing",
        "Debugging",
        "Performance",
        "Observability",
        "Code Quality",
        "Linting",
        "Quality Control",
        "Migration",
        "Analytics",
        "Data",
        "Databases",
    ],
    "📚 Content & Knowledge": [
        "Content",
        "Documentation",
        "Knowledge Management",
        "Diagrams",
        "Design",
        "Communications",
        "Social Media",
        "Localization",
        "Personas",
    ],
    "🧘 Specialized & Lifestyle": [
        "Psychology",
        "Health",
        "Mental Health",
        "Fitness",
        "Sleep",
        "Rehabilitation",
        "Traditional Medicine",
        "Occupational Health",
        "Oral Health",
        "Sexual Health",
        "Travel Health",
    ],
    "⚙️ System & Workflow": ["Core Workflow", "Uncategorized"],
}
